#ifndef B_SHARP_NODETYPENEW_HPP
#define B_SHARP_NODETYPENEW_HPP

#include <cstdint>

enum NodeType : uint8_t {
    PROGRAM, UNARY, BINARY, VARIABLE_ACCESS, VARIABLE_ASSIGN, VALUE,
};

#endif //B_SHARP_NODETYPE_HPP
